In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('/Users/bdlab/Desktop/sparse-matrix-multiplication/scenario-extraction/d-optimal/spmm-of-d-optimal-data/lr-150000-lc-100000-rc-50000/1293-spmm-over-3s-without-add-feature.csv')  
df

,lr,lc,rc,ld,rd,lnnz,rnnz,sp_smdm,bz_smsm,bz_smdm
0,97366,33288,5958,0.000563,0.130,1823595,25785518,32623,76241,73181
1,37277,6335,8305,0.000153,0.200,36129,10524778,5402,4022,6577
2,122335,65522,2027,0.000411,0.250,3294205,33216643,31856,50312,47826
3,85283,55401,5954,0.000017,0.130,78006,42884765,22248,5405,10935
4,88648,49392,11945,0.002962,0.005,12968430,2949991,339996,53227,908915
...,...,...,...,...,...,...,...,...,...,...
1288,94741,3356,15316,0.004916,0.150,1563061,7710242,53350,149334,151154
1289,45728,52231,6071,0.004916,0.200,11741599,63419426,138506,122161,369161
1290,25845,6614,29098,0.010843,0.200,1853575,38494486,78693,146114,280707
1291,94177,8312,10788,0.000319,0.250,250056,22421007,19914,56150,17318
1292,147930,31432,996,0.000319,0.070,1485205,2193518,5399,9109,13536

In [2]:
feature = df[['lr','lc','rc','ld','rd','lnnz','rnnz']]
target = df[['sp_smdm','bz_smsm','bz_smdm']]

In [3]:
import math

lrlc_list=[]
lcrc_list=[]
lrrc_list=[]
lrlcrc_list=[]
ldrd_list=[]
lrrcldrd_list=[]
lrlcrcldrd_list=[]

for i in range(len(df)):
    lrlc_list.append(feature.iloc[i,0] * feature.iloc[i,1])
    lcrc_list.append(feature.iloc[i,1] * feature.iloc[i,2])
    lrrc_list.append(feature.iloc[i,0] * feature.iloc[i,2])
    lrlcrc_list.append(feature.iloc[i,0] * feature.iloc[i,1] * feature.iloc[i,2])
    ldrd_list.append(feature.iloc[i,3] * feature.iloc[i,4])
    lrrcldrd_list.append(feature.iloc[i,0] * feature.iloc[i,2] * feature.iloc[i,3] * feature.iloc[i,4])
    lrlcrcldrd_list.append(feature.iloc[i,0] * feature.iloc[i,1] * feature.iloc[i,2] * feature.iloc[i,3] * feature.iloc[i,4])

In [4]:
lrlc_df = pd.DataFrame(lrlc_list,columns=['lr*lc'])
lcrc_df = pd.DataFrame(lcrc_list,columns=['lc*rc'])
lrrc_df = pd.DataFrame(lrrc_list,columns=['lr*rc'])
lrlcrc_df = pd.DataFrame(lrlcrc_list,columns=['lr*lc*rc'])
ldrd_df = pd.DataFrame(ldrd_list,columns=['ld*rd'])
lrrcldrd_df = pd.DataFrame(lrrcldrd_list,columns=['lr*rc*ld*rd'])
lrlcrcldrd_df = pd.DataFrame(lrlcrcldrd_list,columns=['lr*lc*rc*ld*rd'])

add_feature = pd.concat([lrlc_df,lcrc_df,lrrc_df,lrlcrc_df,ldrd_df,lrrcldrd_df,lrlcrcldrd_df],axis=1) 
add_feature

,lr*lc,lc*rc,lr*rc,lr*lc*rc,ld*rd,lr*rc*ld*rd,lr*lc*rc*ld*rd
0,3241119408,198329904,580106628,19310589432864,0.000073,4.243010e+04,1.412413e+09
1,236149795,52612175,309585485,1961224047475,0.000031,9.471458e+03,6.000169e+07
2,8015633870,132813094,247973045,16247689854490,0.000103,2.547737e+04,1.669328e+09
3,4724763483,329857554,507774982,28131241777782,0.000002,1.089837e+03,6.037808e+07
4,4378502016,589987440,1058900360,52301206581120,0.000015,1.568147e+04,7.745390e+08
...,...,...,...,...,...,...,...
1288,317950796,51400496,1451053156,4869734391536,0.000737,1.070000e+06,3.590920e+09
1289,2388419168,317094401,277614688,14500092768928,0.000983,2.729491e+05,1.425640e+10
1290,170938830,192454172,752037810,4973978075340,0.002169,1.630797e+06,1.078609e+10
1291,782799224,89669856,1015981476,8444838028512,0.000080,8.112866e+04,6.743414e+08
1292,4649735760,31306272,147338280,4631136816960,0.000022,3.294292e+03,1.035462e+08

In [5]:
total_feature = pd.concat([feature, add_feature],axis=1) 
total_feature

,lr,lc,rc,ld,rd,lnnz,rnnz,lr*lc,lc*rc,lr*rc,lr*lc*rc,ld*rd,lr*rc*ld*rd,lr*lc*rc*ld*rd
0,97366,33288,5958,0.000563,0.130,1823595,25785518,3241119408,198329904,580106628,19310589432864,0.000073,4.243010e+04,1.412413e+09
1,37277,6335,8305,0.000153,0.200,36129,10524778,236149795,52612175,309585485,1961224047475,0.000031,9.471458e+03,6.000169e+07
2,122335,65522,2027,0.000411,0.250,3294205,33216643,8015633870,132813094,247973045,16247689854490,0.000103,2.547737e+04,1.669328e+09
3,85283,55401,5954,0.000017,0.130,78006,42884765,4724763483,329857554,507774982,28131241777782,0.000002,1.089837e+03,6.037808e+07
4,88648,49392,11945,0.002962,0.005,12968430,2949991,4378502016,589987440,1058900360,52301206581120,0.000015,1.568147e+04,7.745390e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1288,94741,3356,15316,0.004916,0.150,1563061,7710242,317950796,51400496,1451053156,4869734391536,0.000737,1.070000e+06,3.590920e+09
1289,45728,52231,6071,0.004916,0.200,11741599,63419426,2388419168,317094401,277614688,14500092768928,0.000983,2.729491e+05,1.425640e+10
1290,25845,6614,29098,0.010843,0.200,1853575,38494486,170938830,192454172,752037810,4973978075340,0.002169,1.630797e+06,1.078609e+10
1291,94177,8312,10788,0.000319,0.250,250056,22421007,782799224,89669856,1015981476,8444838028512,0.000080,8.112866e+04,6.743414e+08
1292,147930,31432,996,0.000319,0.070,1485205,2193518,4649735760,31306272,147338280,4631136816960,0.000022,3.294292e+03,1.035462e+08

In [6]:
total_feature.to_csv('/Users/bdlab/Desktop/sparse-matrix-multiplication/scenario-extraction/d-optimal/spmm-of-d-optimal-data/lr-150000-lc-100000-rc-50000/1293-spmm-over-3s.csv', index=False)   # csv ì €ìž¥ì‹œ index ì œê±°